// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcfl44_36iGxwB2FjPGq_KL5urgo0PEXQ',
    appId: '1:852177832034:web:a3f76ff33006cf8183693b',
    messagingSenderId: '852177832034',
    projectId: 'homework-1a9c3',
    authDomain: 'homework-1a9c3.firebaseapp.com',
    storageBucket: 'homework-1a9c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEsI2azvQ1DVxRLMAU-X0L65w2FJXrLoM',
    appId: '1:852177832034:android:a968d368509f64ad83693b',
    messagingSenderId: '852177832034',
    projectId: 'homework-1a9c3',
    storageBucket: 'homework-1a9c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOni_IdzCkQUxSJYJfPOhHgMBoygaiIdg',
    appId: '1:852177832034:ios:6c737a9dd4a8a2d483693b',
    messagingSenderId: '852177832034',
    projectId: 'homework-1a9c3',
    storageBucket: 'homework-1a9c3.firebasestorage.app',
    iosBundleId: 'com.example.homework',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOni_IdzCkQUxSJYJfPOhHgMBoygaiIdg',
    appId: '1:852177832034:ios:6c737a9dd4a8a2d483693b',
    messagingSenderId: '852177832034',
    projectId: 'homework-1a9c3',
    storageBucket: 'homework-1a9c3.firebasestorage.app',
    iosBundleId: 'com.example.homework',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcfl44_36iGxwB2FjPGq_KL5urgo0PEXQ',
    appId: '1:852177832034:web:d986f267178235f383693b',
    messagingSenderId: '852177832034',
    projectId: 'homework-1a9c3',
    authDomain: 'homework-1a9c3.firebaseapp.com',
    storageBucket: 'homework-1a9c3.firebasestorage.app',
  );
}
